[package]
name = "secret_sharing_app"
version = "0.0.2"
description = "A secret sharing app built with Nuxt.js and Tauri"
authors = ["you"]
license = "MIT"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "secret_sharing_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
blahaj = "0.6"
base64 = "0.23"

[dev-dependencies]
rand = "0.10"
